<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kategoripilih kategoriZumbaMuay Thai te_2f0de7</name>
   <tag></tag>
   <elementGuidId>064527ff-f8fc-4ea4-b178-ca2be0e3fd47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/form/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5388dd1-ab01-4954-adba-80122daaa07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex gap-x-5 w-full justify-between</value>
      <webElementGuid>81ef8cb2-12c0-400b-979e-d0fbfe54fa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategoripilih kategoriZumbaMuay Thai testMuay Thai 468Muay Thai 40Muay Thai305Muay Thai 38Muay Thai240Muay Thai 240Muay Thai464Muay Thai 464Muay ThaiMuay Thai286Muay Thai 286Muay Thai31Muay Thai 31Muay Thai207Muay Thai 207Muay Thai 4Muay Thai 229CobaZumba test 2Muay Thai 82Zumbaa niMuay Thai480Pilates 480Muay Thai60Muay Thai2Muay Thai302Muay Thai415Muay Thai462Muay Thai179Zumba gym</value>
      <webElementGuid>525cd7b6-ac56-45c3-ae2c-870cf8bec434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/form[1]/div[@class=&quot;flex flex-col gap-y-3&quot;]/div[@class=&quot;flex gap-x-5 w-full justify-between&quot;]</value>
      <webElementGuid>f1393e1c-4da0-47f8-a9f5-0c0e75e80ccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/form/div/div[3]</value>
      <webElementGuid>938956af-822b-4b3e-b7a5-4a252062a858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi'])[1]/following::div[1]</value>
      <webElementGuid>69b1d831-1f0f-4705-90ed-ef880c58b6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga'])[1]/following::div[2]</value>
      <webElementGuid>1969c6a7-888b-4cfb-810c-953f48cae4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto'])[1]/preceding::div[2]</value>
      <webElementGuid>85f14e88-ca56-4313-9527-80b29718334f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>7bb82091-c48e-442d-b114-b5436ddd891e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kategoripilih kategoriZumbaMuay Thai testMuay Thai 468Muay Thai 40Muay Thai305Muay Thai 38Muay Thai240Muay Thai 240Muay Thai464Muay Thai 464Muay ThaiMuay Thai286Muay Thai 286Muay Thai31Muay Thai 31Muay Thai207Muay Thai 207Muay Thai 4Muay Thai 229CobaZumba test 2Muay Thai 82Zumbaa niMuay Thai480Pilates 480Muay Thai60Muay Thai2Muay Thai302Muay Thai415Muay Thai462Muay Thai179Zumba gym' or . = 'Kategoripilih kategoriZumbaMuay Thai testMuay Thai 468Muay Thai 40Muay Thai305Muay Thai 38Muay Thai240Muay Thai 240Muay Thai464Muay Thai 464Muay ThaiMuay Thai286Muay Thai 286Muay Thai31Muay Thai 31Muay Thai207Muay Thai 207Muay Thai 4Muay Thai 229CobaZumba test 2Muay Thai 82Zumbaa niMuay Thai480Pilates 480Muay Thai60Muay Thai2Muay Thai302Muay Thai415Muay Thai462Muay Thai179Zumba gym')]</value>
      <webElementGuid>5354fad4-1166-4af0-83e6-5718bc5f15b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
