<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Edit</name>
   <tag></tag>
   <elementGuidId>5c1f24f2-566e-4589-99f8-4a838cb97690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div[3]/div/div[4]/div[2]/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5ddeddb2-57f4-4769-8267-9aa258228323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnp w-full text-center  </value>
      <webElementGuid>2eb0eb10-1044-42c5-b0be-d38b31cf1496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>8e9bbc5b-78a0-4cd9-ad97-39bb425612d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;relative&quot;]/div[1]/div[@class=&quot;bg-white my-2 p-2&quot;]/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/div[@class=&quot;w-[300px] border overflow-hidden shadow-xl rounded-xl h-[400px] bg-white&quot;]/div[@class=&quot;flex  justify-between flex-col h-full p-3 items-center&quot;]/div[@class=&quot;flex flex-col w-full  gap-y-2 pb-3 justify-end&quot;]/label[@class=&quot;btnp w-full text-center&quot;]</value>
      <webElementGuid>e6a2d797-35bd-43e5-aedd-0f28dc98e3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>949c1348-b2d4-4f2b-8dc1-a067bb2a34a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnp w-full text-center  </value>
      <webElementGuid>c688296a-fb78-4935-bf65-0df34ab30a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>26f3267a-afc7-48fd-9418-48f5e4053ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;relative&quot;]/div[1]/div[@class=&quot;bg-white my-2 p-2&quot;]/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/div[@class=&quot;w-[300px] border overflow-hidden shadow-xl rounded-xl h-[400px] bg-white&quot;]/div[@class=&quot;flex  justify-between flex-col h-full p-3 items-center&quot;]/div[@class=&quot;flex flex-col w-full  gap-y-2 pb-3 justify-end&quot;]/label[@class=&quot;btnp w-full text-center&quot;]</value>
      <webElementGuid>9426caff-b0d8-4eb9-b500-81a92b9ffcb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[3]/div/div[4]/div[2]/div[2]/label</value>
      <webElementGuid>89d3927f-9c03-4588-8b58-0b350c69214f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 350.000/Bulan'])[1]/following::label[1]</value>
      <webElementGuid>d5a7bb45-1fcb-4cef-b10e-e0a636814f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gold'])[1]/following::label[1]</value>
      <webElementGuid>5591c0b2-3986-4d1d-87a3-f7f75c45ef20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[4]/preceding::label[1]</value>
      <webElementGuid>59270b37-7211-4cbc-9912-3c265e66646c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::label[3]</value>
      <webElementGuid>1979746b-6b03-4c7f-a781-a3cbcfd63153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/label</value>
      <webElementGuid>f66d144b-0f3f-49ad-9dac-a1668d93a684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>6252aa35-bede-4e24-b947-0317ae45b8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[3]/div/div[5]/div[2]/div[2]/label</value>
      <webElementGuid>4de45aca-30cd-499c-a4f0-34d76d22be90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[5]/preceding::label[1]</value>
      <webElementGuid>c166ce92-7e82-4702-86b3-5f62d4b6a317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/label</value>
      <webElementGuid>3e46422b-58c2-4430-ba45-6f28e2aeaf73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
