<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Edit_bx bx-sm rounded-lg bg-dang p-1 text_d9d74a</name>
   <tag></tag>
   <elementGuidId>5395ddd4-3c80-4dc2-bef7-e06ad21d1591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div[3]/div[3]/div/div[2]/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>936411b2-fc0e-47f8-bd04-0f1fa059eb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-sm rounded-lg bg-dang p-1 text-white bx-trash</value>
      <webElementGuid>9e2a6286-b624-4e16-a150-8aca4178f554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[2]/div[@class=&quot;form-control&quot;]/div[@class=&quot;grid mt-5 gap-x-3 gap-y-5 grid-cols-3&quot;]/div[@class=&quot;card w-[320px]  h-72 bg-base-100 shadow-xl&quot;]/div[@class=&quot;px-2 py-2&quot;]/div[@class=&quot;w-full flex mt-2 gap-x-2 items-center justify-between&quot;]/button[@class=&quot;rounded-lg active:scale-95 text-center cursor-pointer transition-all duration-100 ease-linear leading-none&quot;]/i[@class=&quot;bx bx-sm rounded-lg bg-dang p-1 text-white bx-trash&quot;]</value>
      <webElementGuid>1b1068e9-7b7a-4f99-b96e-ed285651a807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[3]/div[3]/div/div[2]/button[2]/i</value>
      <webElementGuid>3567fe03-3555-4e08-b6e1-c49a0125bebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button[2]/i</value>
      <webElementGuid>4749c167-458d-4c3e-90a9-d6c4b48dc379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
