<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_superadmin</name>
   <tag></tag>
   <elementGuidId>b8d32717-149f-400e-9822-957b5bfa8158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/nav/div/ul/div[3]/button/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>ab8ee827-ff5d-456d-bc77-b6773640e86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>superadmin</value>
      <webElementGuid>b98ba118-aa73-47c8-a8bd-c453e36d2772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/nav[@class=&quot;w-full sticky h-[70px] z-50  bg-base/60 border px-4 py-2  flex items-center justify-end&quot;]/div[1]/ul[@class=&quot;flex&quot;]/div[@class=&quot;dropdown dropdown-bottom&quot;]/button[@class=&quot;px-16 pl-2 text-start&quot;]/b[1]</value>
      <webElementGuid>84c6b22f-2c08-4189-9abf-b68bdb58aa9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/ul/div[3]/button/b</value>
      <webElementGuid>dffd66e0-02b5-4bf8-acd3-aa67b6ada2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/preceding::b[1]</value>
      <webElementGuid>e6f76882-6a54-41b2-9981-4e001c0f64df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='superadmin']/parent::*</value>
      <webElementGuid>1b938277-3410-4e3f-ad13-7a7d62a1959c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>a4eba41a-bb28-4ccb-9ad0-7298185956d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'superadmin' or . = 'superadmin')]</value>
      <webElementGuid>8edbce08-9782-4911-8032-e9b05075b5ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
