<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail</name>
   <tag></tag>
   <elementGuidId>c53d4cbf-514d-40aa-89e9-81f7d3053f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[3]/table/tbody/tr[7]/td[8]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4b1ce37-ec20-47d6-a98b-c6c2939842e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnp</value>
      <webElementGuid>88b82268-6b7a-451a-b9fc-220e5edfbc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>789a8f03-1c30-4192-9739-663af023d113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;overflow-x-auto&quot;]/table[@class=&quot;table table-compact text-black w-full&quot;]/tbody[1]/tr[@class=&quot;font-semibold&quot;]/td[@class=&quot;flex gap-x-1&quot;]/button[@class=&quot;btnp&quot;]</value>
      <webElementGuid>390bbcb5-8dcb-437a-a91c-c457817e9a00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[3]/table/tbody/tr[7]/td[8]/button</value>
      <webElementGuid>4a3a16ed-a40f-414a-ad36-a19f2fef196d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENDING'])[1]/following::button[1]</value>
      <webElementGuid>8caf2d4e-feec-45e3-9471-d6003ab8cd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rannida@gmail.com'])[1]/following::button[1]</value>
      <webElementGuid>27509997-065e-4eed-863e-b01666221892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zaki'])[1]/preceding::button[2]</value>
      <webElementGuid>975df250-0150-42ee-a331-d5058f6b3cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zaki@gmail.com'])[1]/preceding::button[2]</value>
      <webElementGuid>c22e41fd-0011-47e6-9b48-81a12466dce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[8]/button</value>
      <webElementGuid>c3d855bd-9d77-499c-9f43-d143f2066db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>2785002a-38bc-4b5a-88fb-2a1ec8b27496</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
