<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Transfer Bank BCABulskeyTransfer Ban_e85f99</name>
   <tag></tag>
   <elementGuidId>658e4f38-a289-4362-bf64-08098f0e974c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='payment_method_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;payment_method_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3d5b3743-f416-4f6b-9347-1262a6113a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method_id</value>
      <webElementGuid>e970f32a-0a7f-4db3-a120-cde0ef8286ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfer Bank BCABulskeyTransfer Bank DKITransfer Bank BRIBank BNI</value>
      <webElementGuid>46dfef36-9236-4d7e-b205-40749df7a94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-box  p-0 overflow-hidden w-1/2&quot;]/div[@class=&quot;w-full p-3 bg-base2 flex&quot;]/div[@class=&quot;w-full relative&quot;]/form[@class=&quot;flex flex-col gap-y-2&quot;]/div[@class=&quot;flex gap-x-4&quot;]/select[1]</value>
      <webElementGuid>7e2ba161-505f-4845-8991-4052d7a13b87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='payment_method_id']</value>
      <webElementGuid>b3c833f6-55af-4074-993e-4ff1ad2d12b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div/form/div[2]/select</value>
      <webElementGuid>61086364-22a7-411b-8404-05f292e8db22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih metode Pembayaran :'])[1]/following::select[1]</value>
      <webElementGuid>ef8ee1a7-0a3e-4476-98b3-cf16ebaf75e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kelas Offline :'])[1]/following::select[2]</value>
      <webElementGuid>71136068-2e16-410b-b4dc-b2fde41a5ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Harga'])[1]/preceding::select[1]</value>
      <webElementGuid>4abca77d-5e0d-4a7d-a4cb-da72fb0a666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>9b37066d-a4c4-4f4f-87ab-437265290660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>bb59e91f-cd01-47db-8575-5bad0743362a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'payment_method_id' and (text() = 'Transfer Bank BCABulskeyTransfer Bank DKITransfer Bank BRIBank BNI' or . = 'Transfer Bank BCABulskeyTransfer Bank DKITransfer Bank BRIBank BNI')]</value>
      <webElementGuid>fd1d8e32-9282-47b2-a0d3-6fb7da8ef552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
