<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_sassasasassasnotifZumba gymZumba gym_059042</name>
   <tag></tag>
   <elementGuidId>dc376705-0c34-40de-90bb-afd456945ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='offline_class_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;offline_class_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ae40809-5649-4854-a11e-e97770994f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offline_class_id</value>
      <webElementGuid>2747e502-682c-4280-969a-603bf4f92db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sassasasassasnotifZumba gymZumba gymZumba gymapaaaagmeet2gmeet2kelas gmeetwqwqwqzumbaaaaaazumbaakelas bisacobaaasaszunvaaasasahalolatihan pagikelas traineZumba Internasional ClassOffline LengkapOffline LengkapKelas offlineZumba Internasional ClassZumba2Zumba Internasional Class</value>
      <webElementGuid>2b2ee3ed-3748-4629-8b12-af59e219493f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-box  p-0 overflow-hidden w-1/2&quot;]/div[@class=&quot;w-full p-3 bg-base2 flex&quot;]/div[@class=&quot;w-full relative&quot;]/form[@class=&quot;flex flex-col gap-y-2&quot;]/div[@class=&quot;flex gap-x-4&quot;]/select[1]</value>
      <webElementGuid>c3d33bd8-292e-47ab-88c5-baa85ebc3f10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='offline_class_id']</value>
      <webElementGuid>a4face48-df3a-4965-bc0e-0ffd83499101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/div/form/div/select</value>
      <webElementGuid>a1c6c1a8-8154-41cb-8cc7-6097b7363695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kelas Offline :'])[1]/following::select[1]</value>
      <webElementGuid>0b03f06a-4733-42ce-b295-ddc51190e568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Booking Online'])[1]/following::select[1]</value>
      <webElementGuid>8e043feb-02c9-478b-8908-2e1d23ce1b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih metode Pembayaran :'])[1]/preceding::select[1]</value>
      <webElementGuid>928ef4a4-ffb4-4128-b734-fac37d18fb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Harga'])[1]/preceding::select[2]</value>
      <webElementGuid>519e9cfd-1673-478f-a85d-0252e86598e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>973409d3-7e25-4ae9-8f54-1c6655be7673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'offline_class_id' and (text() = 'sassasasassasnotifZumba gymZumba gymZumba gymapaaaagmeet2gmeet2kelas gmeetwqwqwqzumbaaaaaazumbaakelas bisacobaaasaszunvaaasasahalolatihan pagikelas traineZumba Internasional ClassOffline LengkapOffline LengkapKelas offlineZumba Internasional ClassZumba2Zumba Internasional Class' or . = 'sassasasassasnotifZumba gymZumba gymZumba gymapaaaagmeet2gmeet2kelas gmeetwqwqwqzumbaaaaaazumbaakelas bisacobaaasaszunvaaasasahalolatihan pagikelas traineZumba Internasional ClassOffline LengkapOffline LengkapKelas offlineZumba Internasional ClassZumba2Zumba Internasional Class')]</value>
      <webElementGuid>3bc1eaf7-4058-421c-b5f8-0570aec0bb7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
