<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Tambah Jenis_bx bx-user-plus bx-sm</name>
   <tag></tag>
   <elementGuidId>2c154c1d-0da5-4857-ad6f-c89410542da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/label/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bx.bx-user-plus.bx-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>40bbaa26-1f6c-4e38-8ade-b9eb0f71e3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-user-plus bx-sm</value>
      <webElementGuid>2e3d3904-66f9-4c3d-be92-40fc42851561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;relative&quot;]/div[1]/div[@class=&quot;pt-2 flex justify-end&quot;]/label[@class=&quot;btn text-primary border-primary bg-base hover:bg-primary hover:text-white transition duration-200 ease-in hover:border-base&quot;]/i[@class=&quot;bx bx-user-plus bx-sm&quot;]</value>
      <webElementGuid>ddfe822d-0490-4630-9fd9-85672e2ce87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/label/i</value>
      <webElementGuid>ebef5ec7-1d5b-4049-9b7b-bfa630558fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>fdf8fc48-220a-4990-b111-090a53578da0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
