<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trainer_access_gym</name>
   <tag></tag>
   <elementGuidId>1684060f-55ea-433e-bce1-1f528ee9cb14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='access_gym']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;access_gym&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>045cf5c9-ee95-42f3-a5d7-2cee3fae1687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox rounded-none checkbox-accent h-5 w-5  block py-1 my-1</value>
      <webElementGuid>1434347c-c2d9-41a5-a7aa-2d26a3daf7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>aa31bae7-620c-42f2-8bb2-17014e451ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>access_gym</value>
      <webElementGuid>b92ebbe7-dac0-4e81-ad9c-e1e9caf30002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f3115b7-580c-498b-992d-e3c090d1c963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-box   p-0 overflow-hidden w-1/2 max-w-5xl&quot;]/form[1]/div[@class=&quot;p-3&quot;]/div[@class=&quot;flex w-full px-2 gap-x-2&quot;]/div[@class=&quot;w-[50%]&quot;]/div[@class=&quot;w-full  border px-1&quot;]/div[@class=&quot;flex gap-x-2&quot;]/input[@class=&quot;checkbox rounded-none checkbox-accent h-5 w-5  block py-1 my-1&quot;]</value>
      <webElementGuid>5e812589-b9e5-4269-9157-666af86eab47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='access_gym']</value>
      <webElementGuid>ae598107-35bc-47ee-b42d-cae090be1dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/form/div/div/div[3]/div/div[4]/input</value>
      <webElementGuid>221ec7d2-c106-4d22-9288-baff38d0f4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>71d80312-ecf2-44ec-ae7e-e33159d94103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'access_gym']</value>
      <webElementGuid>a97f1719-0a8d-4cd4-a75f-eb47201d7c8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
