<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fitur Yang ditawarkan_access_offline_class</name>
   <tag></tag>
   <elementGuidId>2f2c38a8-4a62-4c70-9758-66a365c537ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='access_offline_class']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;access_offline_class&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>809876bf-23b6-4a1e-96ef-5ac317899455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox rounded-none checkbox-accent h-5 w-5 block py-1 my-1</value>
      <webElementGuid>04319f5d-b8e6-475d-af6e-6fc995a36547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>01c668c1-611b-4104-bc09-db9f98a9e53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>access_offline_class</value>
      <webElementGuid>24cd1617-53e4-4809-96ad-a51bf5ba4849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c69f3e05-62dc-4a7e-be14-7703ca0a1254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-box   p-0 overflow-hidden w-1/2 max-w-5xl&quot;]/form[1]/div[@class=&quot;p-3&quot;]/div[@class=&quot;flex w-full px-2 gap-x-2&quot;]/div[@class=&quot;w-[50%]&quot;]/div[@class=&quot;w-full  border px-1&quot;]/div[@class=&quot;flex gap-x-2&quot;]/input[@class=&quot;checkbox rounded-none checkbox-accent h-5 w-5 block py-1 my-1&quot;]</value>
      <webElementGuid>1f101608-32dc-4e04-b972-15703336ee12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='access_offline_class']</value>
      <webElementGuid>78f15a58-a8a9-4c7a-872e-76877bfd8dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/form/div/div/div[3]/div/div/input</value>
      <webElementGuid>ba66e68e-ff2f-4353-ba15-f8574e67caa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>7a66e43c-3b1e-4260-8cdc-bae3dc306236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'access_offline_class']</value>
      <webElementGuid>fdaaf5f6-9b51-4f2d-8127-b34a0ecfc7ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
