<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_hola_w-32</name>
   <tag></tag>
   <elementGuidId>d56311a7-032f-4e53-8f2f-cca30a7eac4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/ul/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-32</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>041c9d7d-dab6-40c7-bd41-f57ed2581d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-32</value>
      <webElementGuid>159dcb9f-289b-4a3c-87f4-19cf1b3e1077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/logo.edf9d40040b5f09559b1.png</value>
      <webElementGuid>9a07437c-dd90-4c2c-b17f-4ca352ceef96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-side border&quot;]/ul[@class=&quot;menu p-4 w-60 text-[#222222] e&quot;]/a[@class=&quot;mb-2 flex justify-center&quot;]/img[@class=&quot;w-32&quot;]</value>
      <webElementGuid>c9cb13b9-886b-4081-ba4a-1c57f235381e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/ul/a/img</value>
      <webElementGuid>d6da23ca-ce16-4947-ba77-afc6c226b27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/a/img</value>
      <webElementGuid>19ff743c-a738-41ca-aed3-dfd3c3088792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/logo.edf9d40040b5f09559b1.png']</value>
      <webElementGuid>5f569524-c10b-4655-8473-4ea18c9f166c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
