<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Edit</name>
   <tag></tag>
   <elementGuidId>c440bc16-6fa3-4404-b301-7ce54923bc3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ac31e807-a139-4c42-8a5a-eef5de8dd5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnp w-full text-center  </value>
      <webElementGuid>84955aec-ff4c-4fd4-82cc-25201d01a97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>4a6bc56e-7493-4333-8d35-98cff032f9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;relative&quot;]/div[1]/div[@class=&quot;bg-white my-2 p-2&quot;]/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/div[@class=&quot;w-[300px] border overflow-hidden shadow-xl rounded-xl h-[400px] bg-white&quot;]/div[@class=&quot;flex  justify-between flex-col h-full p-3 items-center&quot;]/div[@class=&quot;flex flex-col w-full  gap-y-2 pb-3 justify-end&quot;]/label[@class=&quot;btnp w-full text-center&quot;]</value>
      <webElementGuid>d66e3960-aac3-44c0-bfc0-3725a2d905e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[2]/label</value>
      <webElementGuid>9e6e7753-20b5-4f80-ae8b-122c79f7f919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 500.000/Bulan'])[1]/following::label[1]</value>
      <webElementGuid>c69e7ea7-a499-4b6c-bf62-d375af247bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum'])[1]/following::label[1]</value>
      <webElementGuid>4df4a7cd-1e62-4e93-8be9-35b870786318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::label[1]</value>
      <webElementGuid>0532b3fa-48a8-4594-a141-68fa279371e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bronze'])[1]/preceding::label[2]</value>
      <webElementGuid>8a0884fc-086b-4717-a568-e2bde22b40d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>0c068890-a264-42a0-931d-b52fa3bc1532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label</value>
      <webElementGuid>242707a1-a20d-4993-8e85-3c979e4e974b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>61c63770-bb65-476f-a667-97dcc53e6df2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
