<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ya</name>
   <tag></tag>
   <elementGuidId>98f60b0e-ad6a-40e7-b9e3-804b7b0e2d9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>027398d9-512c-408d-a094-cddd24eb5b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modal-toggle</name>
      <type>Main</type>
      <value>popup-modal</value>
      <webElementGuid>5a5bce6c-cd28-4af4-ae4e-1fef28539da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08386e3a-9f3a-4d91-9be3-4b4b7d6fe444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white bg-prim hover:bg-prim/70  font-medium rounded-lg text-sm inline-flex items-center px-8 py-2 text-center mr-2</value>
      <webElementGuid>d848c62c-958b-4eca-b6e1-1de268dcfb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>cc3fc84d-9cc3-4591-b8c2-2bee877262e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;relative w-full h-full max-w-md md:h-auto&quot;]/div[@class=&quot;relative bg-white rounded-lg shadow&quot;]/div[@class=&quot;p-6 text-center&quot;]/button[@class=&quot;text-white bg-prim hover:bg-prim/70  font-medium rounded-lg text-sm inline-flex items-center px-8 py-2 text-center mr-2&quot;]</value>
      <webElementGuid>80224246-9349-4ce3-9f7f-0ec599705ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9209c3e1-c059-4415-86a4-41917f7db545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modal-toggle</name>
      <type>Main</type>
      <value>popup-modal</value>
      <webElementGuid>ecc5b286-5dfb-4d19-981d-0b858cc65b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7939a63a-3939-441d-b719-00cead9900c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white bg-prim hover:bg-prim/70  font-medium rounded-lg text-sm inline-flex items-center px-8 py-2 text-center mr-2</value>
      <webElementGuid>69cd0259-137d-40c3-9752-ba363a0a5429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>68bc3004-15b3-4de4-9c70-7eb9c85846fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;relative w-full h-full max-w-md md:h-auto&quot;]/div[@class=&quot;relative bg-white rounded-lg shadow&quot;]/div[@class=&quot;p-6 text-center&quot;]/button[@class=&quot;text-white bg-prim hover:bg-prim/70  font-medium rounded-lg text-sm inline-flex items-center px-8 py-2 text-center mr-2&quot;]</value>
      <webElementGuid>fede3e56-9911-490e-857b-2bbc05ae2506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2bae665-1a57-4b09-9779-4e0cbc0aa258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modal-toggle</name>
      <type>Main</type>
      <value>popup-modal</value>
      <webElementGuid>7e7840c8-5567-4a9a-8399-0cc30e96d12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc399e03-ebbf-4442-95ef-460922c1ed3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white bg-prim hover:bg-prim/70  font-medium rounded-lg text-sm inline-flex items-center px-8 py-2 text-center mr-2</value>
      <webElementGuid>2293ef3d-7797-4f24-96d7-c0aa8cc38a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>b0960a86-0e87-4e4b-871c-dd835b7e704c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;relative w-full h-full max-w-md md:h-auto&quot;]/div[@class=&quot;relative bg-white rounded-lg shadow&quot;]/div[@class=&quot;p-6 text-center&quot;]/button[@class=&quot;text-white bg-prim hover:bg-prim/70  font-medium rounded-lg text-sm inline-flex items-center px-8 py-2 text-center mr-2&quot;]</value>
      <webElementGuid>b23729f4-9e17-415a-97a2-3c826615fa6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>3eda08db-b038-4070-a445-d90cbd882b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>1bafdfc1-c7a2-42c5-b043-5d272cd78e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah anda yakin untuk menghapus'])[1]/following::button[1]</value>
      <webElementGuid>e7654771-cb3c-42f7-b61e-a2643945fbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close modal'])[1]/following::button[1]</value>
      <webElementGuid>499a85fa-479d-4a24-b30a-b93de22fca64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::button[1]</value>
      <webElementGuid>716190ad-ce6c-4e86-91e0-040d66fdec7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Skill'])[1]/preceding::button[2]</value>
      <webElementGuid>a2b1b24c-2cff-4f32-955d-2532eede6e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ya']/parent::*</value>
      <webElementGuid>1f114c74-ef49-44c3-97f9-34af9cb546e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>384fc486-f1cd-4499-a5e9-d830515f39c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ya' or . = 'Ya')]</value>
      <webElementGuid>cce6f304-3b5b-4125-baf0-1a9855ed6455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Trainer'])[1]/preceding::button[2]</value>
      <webElementGuid>cc22a103-f71b-4160-8440-82f2006cf6b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
