<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close modalApakah anda yakin untuk meng_bed613</name>
   <tag></tag>
   <elementGuidId>d510a9d7-5567-4179-8c55-5b8540bd6666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5870bc50-1d71-4262-9f17-88bcb9b9323a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>f12c6244-09c2-4332-837d-01b6a2f69117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close modalApakah anda yakin untuk menghapusYaBatal</value>
      <webElementGuid>352b3c22-ffa5-4787-8bae-207c165bc9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;modal&quot;]</value>
      <webElementGuid>f72906ad-a8f2-450c-a0fa-07ce61b2cf43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div</value>
      <webElementGuid>2b0d720e-bf1d-40b6-9861-5f6f168cab27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/following::div[2]</value>
      <webElementGuid>9e274b39-d0a3-4876-9f5a-612be9c19c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='superadmin'])[1]/following::div[2]</value>
      <webElementGuid>cead0bda-0fe1-451b-9552-8376fef42333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>790755c9-3f24-45e6-8638-e0e0d965cf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Close modalApakah anda yakin untuk menghapusYaBatal' or . = 'Close modalApakah anda yakin untuk menghapusYaBatal')]</value>
      <webElementGuid>133b751b-ea79-464e-8af8-48dc966159d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
