<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_testttt_bx bx-trash-alt</name>
   <tag></tag>
   <elementGuidId>a172b974-1f0d-4e5c-a6fb-d43a7a0679bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bx.bx-trash-alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[3]/div/div/span[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>88dbe6b9-058f-48ce-94c9-f5ca5c5c68ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-trash-alt</value>
      <webElementGuid>2ee7a995-382a-47f3-8677-31b67bd5e1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;grid grid-cols-4&quot;]/div[@class=&quot;w-56  mt-5 relative h-16 border-prim overflow-auto shadow-lg p-1 border bg-white rounded-xl&quot;]/div[@class=&quot;absolute gap-x-2 flex right-0 top-0 px-2&quot;]/span[@class=&quot;cursor-pointer text-prim&quot;]/i[@class=&quot;bx bx-trash-alt&quot;]</value>
      <webElementGuid>e0bd1130-6eab-41fe-a902-fc54397374b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[3]/div/div/span[2]/i</value>
      <webElementGuid>bd30de8b-b19c-4aaf-8ebb-765a23a2c021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>8b46405b-ba3f-4995-b63c-a0f4a46a55a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
