<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Testtt_bx bx-trash-alt</name>
   <tag></tag>
   <elementGuidId>bfdb6a10-2323-4483-86e4-6bb36990258f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bx.bx-trash-alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[3]/div/div/span[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>76b2d939-4153-4c79-876a-92dabeebc662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-trash-alt</value>
      <webElementGuid>40312384-86aa-4cb3-abe5-8d0e53375fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;grid grid-cols-4&quot;]/div[@class=&quot;w-56  mt-5 relative h-16 border-prim overflow-auto shadow-lg p-1 border bg-white rounded-xl&quot;]/div[@class=&quot;absolute gap-x-2 flex right-0 top-0 px-2&quot;]/span[@class=&quot;cursor-pointer text-prim&quot;]/i[@class=&quot;bx bx-trash-alt&quot;]</value>
      <webElementGuid>9c3c65d5-2c1d-4663-adf7-722dbc50900f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[3]/div/div/span[2]/i</value>
      <webElementGuid>eb04f229-272f-4a2a-a4dd-388454c253b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>d4530dde-e358-4fb8-b7e7-602f8bd7348c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
