<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_P_gender</name>
   <tag></tag>
   <elementGuidId>cab1102c-45e8-4958-a4c7-3099efdbfba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='gender'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41f1f574-8dbc-4605-b42f-f7961d198cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bb15cccd-abc6-4409-b1e9-bad12bf72d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>1f4111de-bd3b-4a60-9c19-78f7f9f200d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio radio-accent w-4 h-4</value>
      <webElementGuid>8b125fa8-e9a3-4f6c-97df-8cc55abb4283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>d838e7c9-eb6e-40eb-90c3-863bf7fdfdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-box   p-0 w-full max-w-[60%]&quot;]/form[1]/div[@class=&quot;p-3&quot;]/div[@class=&quot;flex flex-col w-full  px-2 gap-x-4&quot;]/div[@class=&quot;w-full flex gap-x-4&quot;]/div[@class=&quot;w-1/2 text-sm&quot;]/div[4]/div[@class=&quot;flex my-1&quot;]/div[@class=&quot;flex gap-x-2&quot;]/span[@class=&quot;flex items-center gap-x-2&quot;]/input[@class=&quot;radio radio-accent w-4 h-4&quot;]</value>
      <webElementGuid>43aefe74-8cb5-45ed-b836-97b68ab9fb87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='gender'])[2]</value>
      <webElementGuid>138201c9-4352-4e88-bd82-7a8c89508c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/form/div/div/div[2]/div[2]/div[4]/div/div[2]/span/input</value>
      <webElementGuid>c71f1e86-37e5-413c-9c99-281346526cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P'])[1]/input[1]</value>
      <webElementGuid>af5f91aa-2d80-4b9e-b630-a35129ad808c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[1]/following::input[1]</value>
      <webElementGuid>4cd36f2d-2093-4ce4-9d5e-641d2b99f680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi'])[1]/preceding::input[1]</value>
      <webElementGuid>ec888483-ed44-4788-93ac-e5baf4c1bf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='simpan'])[1]/preceding::input[1]</value>
      <webElementGuid>17bded82-bcd2-4bb4-959b-13f1739158da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>c4b83751-82bb-4927-819f-5d5e9835e9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'gender']</value>
      <webElementGuid>c181ac9d-50aa-4261-a142-85c329cbe1d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
