<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga_price</name>
   <tag></tag>
   <elementGuidId>7c9933b6-ca9d-442f-a501-b2295dda1b62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;price&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb2557f4-b00d-4b42-b7ae-6d7317f87d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputTrainer w-full</value>
      <webElementGuid>b8caa04a-d66d-44e5-a616-ddcb90daadb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>410db6f7-e457-4bf9-be40-9f77c1b9236c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>b25f9311-15d5-42b6-b3e0-2b0b4f042e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-box   p-0 w-full max-w-[60%]&quot;]/form[1]/div[@class=&quot;p-3&quot;]/div[@class=&quot;flex flex-col w-full  px-2 gap-x-4&quot;]/div[@class=&quot;w-full flex gap-x-4&quot;]/div[@class=&quot;w-1/2 text-sm&quot;]/div[1]/input[@class=&quot;inputTrainer w-full&quot;]</value>
      <webElementGuid>66736005-df41-4e2e-bc3f-55891360e40f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='price']</value>
      <webElementGuid>b3807ec4-3a3f-41aa-ae6d-347d3e9baa6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/form/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>f454fe71-c70b-48ef-90b8-e361fd2a235b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga'])[1]/following::input[1]</value>
      <webElementGuid>05533802-9367-42e4-9cd1-97bb73ff4d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dob'])[1]/following::input[2]</value>
      <webElementGuid>715a125e-2431-4f22-8160-0034d508d0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slot'])[1]/preceding::input[1]</value>
      <webElementGuid>6ebdb771-d27f-4f8b-aa8b-315357ac1658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trainer'])[1]/preceding::input[2]</value>
      <webElementGuid>56cff0c1-8171-4702-bf84-06261d7063db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>6c175962-e7b2-4058-a3da-5ac712982819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'price']</value>
      <webElementGuid>234c6be9-e00b-45a8-b7f3-4a876a6f6fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
