<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Tambah Kategori</name>
   <tag></tag>
   <elementGuidId>b2975cf9-13d4-4b62-bd4a-b83b4b6d3ffe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>80e9bf13-5708-49ff-aa1c-537661b8dc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>my-modal-5</value>
      <webElementGuid>5881b422-1676-4889-a434-19cde798d2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn border-prim bg-prim hover:bg-accent text-white transition duration-200 ease-in hover:border-base</value>
      <webElementGuid>bf5859e5-d7e9-4638-be93-6b75454c46fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah Kategori</value>
      <webElementGuid>08b9d9bb-d350-4d47-ae27-a323876b5eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[2]/div[@class=&quot;form-control&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;flex justify-end&quot;]/label[@class=&quot;btn border-prim bg-prim hover:bg-accent text-white transition duration-200 ease-in hover:border-base&quot;]</value>
      <webElementGuid>df55a3b6-d4c0-41af-9ccf-d524636d3470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e8401368-e23c-47ca-926e-c3e0c6d8de66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>my-modal-5</value>
      <webElementGuid>074d6a91-4b1f-4466-91f6-59f0f2734618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn border-prim bg-prim hover:bg-accent text-white transition duration-200 ease-in hover:border-base</value>
      <webElementGuid>4fbc8716-7e1b-4127-8049-d3e134f66ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah Kategori</value>
      <webElementGuid>e69d13f2-a962-428f-93a4-e6008bfb634d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;drawer drawer-mobile&quot;]/div[@class=&quot;drawer-content  flex flex-col&quot;]/div[@class=&quot;py-4 px-6&quot;]/div[2]/div[@class=&quot;form-control&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;flex justify-end&quot;]/label[@class=&quot;btn border-prim bg-prim hover:bg-accent text-white transition duration-200 ease-in hover:border-base&quot;]</value>
      <webElementGuid>2dc044f0-e8e1-469a-b32a-9fba7f9b02df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/label</value>
      <webElementGuid>bd412a59-1f3b-4402-b711-93de16cee699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori Kelas Offline'])[1]/following::label[1]</value>
      <webElementGuid>34dd2fdd-659b-4e2e-b373-ce4ea8dafd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/following::label[1]</value>
      <webElementGuid>697ddf8a-1761-45ac-8613-954d4c081a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zumba'])[1]/preceding::label[1]</value>
      <webElementGuid>cecfaa4d-017a-493e-a403-f9310eeb9a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/preceding::label[1]</value>
      <webElementGuid>3b94476d-5fac-4755-bd86-11724ce3084b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Kategori']/parent::*</value>
      <webElementGuid>95c3ab76-f853-473c-b012-1a0def4b3c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>691b7739-b485-4555-9b26-ecfe36519d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Tambah Kategori' or . = ' Tambah Kategori')]</value>
      <webElementGuid>df6e67b7-55e6-4c97-9e43-35541802347b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
